### ISSUE TITLE
no install page

### ISSUE THREAD

**Issue by lidaling** [adaptcms/AdaptCMS#25]
i has published the last package to the php root dir,and i did chmod folders as doc.
however,at last the "http://localhost/adaptcms" change to the nginx index.html page.

what can i do to install successfull

**Comment by lidaling** [comment]
this is the nginx server error log:
2013/10/12 11:12:27 [error] 6761#0: *5 FastCGI sent in stderr: "PHP message: PHP Warning:  require(app/webroot/index.php): failed to open stream: Permission denied in /var/www/cms/adaptcms/index.php on line 40
PHP message: PHP Fatal error:  require(): Failed opening required 'app/webroot/index.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/cms/adaptcms/index.php on line 40" while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /adaptcms/index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "127.0.0.1"

**Comment by charliepage88** [comment]
It sounds like a user permissions issue if you are getting a permission denied error. If you haven't already, you'll need to configure the nginx settings:

http://book.cakephp.org/2.0/en/installation/url-rewriting.html#pretty-urls-on-nginx

If you've done that though, it is sounding like permissions. I see a similar issue here:

http://forum.nginx.org/read.php?2,225554,225554
