### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by advidsec** [adaptcms/AdaptCMS#48]
When i unzip the app and access to my server, the installer do not run automatically.

**Comment by charliepage88** [comment]
Could you check the server logs to see what they say? Also if there is anything in the log file - storage/logs/laravel.log

If you're able to, post what they say here. If you just want to get things going, edit your ".env" file and put in your database credentials there as a shortcut, see if it redirects correctly then.

Thanks!

**Comment by advidsec** [comment]
My access.log:

192.168.127.1 - - [08/Jul/2017:04:32:21 +0200] "GET /adaptcms/ HTTP/1.1" 200 1027 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.127.1 - - [08/Jul/2017:04:32:21 +0200] "GET /icons/blank.gif HTTP/1.1" 304 179 "http://192.168.127.128/adaptcms/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.127.1 - - [08/Jul/2017:04:32:21 +0200] "GET /icons/back.gif HTTP/1.1" 304 179 "http://192.168.127.128/adaptcms/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.127.1 - - [08/Jul/2017:04:32:21 +0200] "GET /icons/text.gif HTTP/1.1" 304 179 "http://192.168.127.128/adaptcms/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.127.1 - - [08/Jul/2017:04:32:21 +0200] "GET /icons/folder.gif HTTP/1.1" 304 180 "http://192.168.127.128/adaptcms/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.127.1 - - [08/Jul/2017:04:32:21 +0200] "GET /icons/unknown.gif HTTP/1.1" 304 180 "http://192.168.127.128/adaptcms/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"

In the laravel.log i do not have any entry :(

My env:
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
SSH_CONNECTION=192.168.127.1 57794 192.168.127.128 22
LANG=es_ES.UTF-8
XDG_SESSION_ID=204
USER=root
PWD=/var/www/html/adaptcms/storage/logs
HOME=/root
SSH_CLIENT=192.168.127.1 57794 22
SSH_TTY=/dev/pts/0
MAIL=/var/mail/root
TERM=xterm
SHELL=/bin/bash
SHLVL=1
LOGNAME=root
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/0/bus
XDG_RUNTIME_DIR=/run/user/0
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
OLDPWD=/var/log/apache2

Regards,

**Comment by charliepage88** [comment]
Sorry for the confusion, could you post the error log instead of the access log from the server?

And could you paste the contents of the ".env" file, looks like it's located at the following on your server:

/var/www/html/adaptcms/.env

Thanks!

**Comment by charliepage88** [comment]
closing this for now due to work being done on beta, for those that experience this issue, try the below:

create file at /storage/logs/laravel.log (empty file)
chmod the storage folder for write permissions, recursively, such as 755

if you get the same issues, install composer and try running the below:
composer update
composer dump-autoload

**Comment by charliepage88** [comment]
some users experienced this error:

`Uncaught ReflectionException: Class db does not exist in `

To fix it, install sqlite on that server or computer. Re-run composer, as described previously, then you should be redirected to installation afterwards. If not, please create an issue with the error(s) you are getting.

Thanks!

**Comment by charliepage88** [comment]
One more follow-up: For beta users, several fixes have been applied to the installer.
