### ISSUE TITLE
4.0 Beta Brainstorming

### ISSUE THREAD

**Issue by charliepage88** [adaptcms/AdaptCMS#54]
# Notice

_This is for anyone to participate with._

What features would you like to see in the beta? Whether it's improving how something works now or something completely new. Let's discuss!

**Comment by Daniel-Yonkov** [comment]
Hey Charlie.
I was thinking about automatic theme generation based on PSD file.
I am not sure yet, how to archive this, but as an Idea, I share it =]

**Comment by charliepage88** [comment]
That sounds very interesting! We'll definitely look into that.
