### ISSUE TITLE
WYSIWYG editor busted

### ISSUE THREAD

**Issue by charliepage88** [adaptcms/AdaptCMS#57]
Need to use new editor. Dependency on VueJS results in fewer choices, but I'm leaning towards this one:

https://yabwe.github.io/medium-editor/

**Comment by marky291** [comment]
Best to use plain java-script for the editor provided by web-pack, editors are way to complex in files and this will never work on VueJS as a single entity.

**Comment by dtadetayo** [comment]
Room Can't we use ckeditor ?

**Comment by dtadetayo** [comment]
Plainjs.com

**Comment by marky291** [comment]
Editors are not made to work with vue officially, they tend to have 20+ files that all depend on each other all read from the public domain of the website, the top guys are tinymce and ckeditor, although packages people have made to attempt a vue conversion it will never be the official implementation.

You can use npm install editor.

Then webpack -> copy to public folder.

**Comment by charliepage88** [comment]
implemented ckeditor for standard wysiwyg

using codemirror for code textareas
