### ISSUE TITLE
Laravel 5.6 version install

### ISSUE THREAD

**Issue by illuminate3** [adaptcms/AdaptCMS#62]
Hi,

I noticed that the seeders seem to be missing. Is this version still under development?

**Comment by illuminate3** [comment]
I redid the install, I set my permissions and added the db name in .env and the installer took over this time.

I am going to keep this open since I did find another error:
```
Class 'App\Modules\Users\Models\App\Modules\Users\ModelFilters\UserFilter' not found
```

I will check into why that is doubling up like that.

**Comment by illuminate3** [comment]
User model:

```

        return $this->provideFilter(\App\Modules\Users\ModelFilters\UserFilter::class);
```

the slash before app cleared that up.

There are several more like this and minor things. I am going to close this for now.

**Comment by charliepage88** [comment]
I appreciate the help! Development has been on hold for a little while but will be starting back again once I get back in town.

I’ll take a look then and fix any outstanding installation issues. Feel free to PR - thanks again!
